name: GitHub Actions Demo

on:
  - push
  - workflow_dispatch

jobs:
  run-my-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Omochice/action-podeno@sandbox
        with:
          config: |
            [
              { type: "markdown", in: "README.pod", out: "README.md", },
              { type: "vimdoc", in: "README.pod", out: "doc/sample.txt", autoMkdir: true, },
            ]
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: update docs"
          branch: ${{ github.head_ref }}

