name: GitHub Actions Demo

on:
  - push
  - workflow_dispatch

jobs:
  run-my-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Omochice/action-podeno@sandbox
        with:
          config: "[{ 'type': 'mardown', 'in': 'README.pod', 'out': 'README.md' }, { 'type': 'vimdoc', 'in': 'README.pod', 'out': 'sample.txt' }]"
      - run: "ls"

