name: GitHub Actions Demo

on:
  - push
  - workflow_dispatch

jobs:
  run-my-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Omochice/action-normalize-vim-plugin-name@dev
        id: normalize
        with:
          trim-tail-dot-vim: true
      - run: echo "${{ steps.normalize.outputs.normalizedName }}"
      - uses: Omochice/action-podeno@v0.1.0
        with:
          config: |
            [
              { type: "markdown", in: "README.pod", out: "README.md", },
              { type: "vimdoc", in: "README.pod", out: "doc/${{ steps.normalize.outputs.normalizedName }}.txt", autoMkdir: true, },
            ]
      # - uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: "docs: update docs"
      #     branch: ${{ github.head_ref }}

