name: GitHub Actions Demo

on:
  - push

jobs:
  run-my-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Omochice/action-podeno@sandbox
        with:
          config: podeno.config.json
      - run: "ls"

